version: '3.4'

services:
  backendapi:
    image: ${DOCKER_REGISTRY-}vsptbackendapi
    build:

      context: .
      dockerfile: Vspt.BackEnd.Api/Dockerfile
      
   

  flagmanapi:
    image: ${DOCKER_REGISTRY-}vsptbackendflagmanapi    
    build:
      context: .
      dockerfile: Vspt.BackEnd.Flagman.Api/Dockerfile
   

  frontend:
    image: ${DOCKER_REGISTRY-}vspt-frontend
  
    build:
      context: .
      dockerfile: Vspt.Frontend/Dockerfile

    

   

  
  
