version: '3.4'

services:
  vspt.backend.api:
    image: ${DOCKER_REGISTRY-}vsptbackendapi
    build:
      context: .
      dockerfile: Vspt.BackEnd.Api/Dockerfile

  vspt.backend.flagman.api:
    image: ${DOCKER_REGISTRY-}vsptbackendflagmanapi
    build:
      context: .
      dockerfile: Vspt.BackEnd.Flagman.Api/Dockerfile

