#!/bin/bash
set -Eeuo pipefail
cd "$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
cd ..
function delete_api_client() {
	local project_name="${1}" && shift
	(
		set -x
		find "./src/Tiss.${project_name}.ApiClients" -name "I${project_name}"'*ApiClient.cs' -print -delete
	)
}
(
	delete_api_client Partner
	delete_api_client Pricing
	delete_api_client Catalog
	delete_api_client Cross
)
