#!/bin/bash
set -Eeuo pipefail
cd "$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
cd ..
set -x
export COMPOSE_FILE=tiss.docker-compose.json
while true
do
	docker compose --profile all logs --follow || true
done
